### ISSUE TITLE
为什么我修改不了图片路径呢？

### ISSUE THREAD

**Issue by MarcoPai** [amazeui/starter-kit#3]
很是奇怪，我把`app/i`目录修改为`app/img`目录之后，运行`gulp serve` 生成后的dist里面的img目录竟然是空的。。。。

然后我又修改回`i`目录再生成之后，奇葩的事情出现了，dist里面竟然有一个i目录和一个img目录，之前我已经做了`gulp clean`

**Comment by minwe** [comment]
https://www.npmjs.com/package/gulp-cache

应该是这个插件作怪，自己加个任务清理缓存：

```js
gulp.task('clear', function(done) {
  return cache.clearAll(done);
});
```

**Comment by MarcoPai** [comment]
我更新下你新提交的这个就可以了吧

**Comment by minwe** [comment]
可以，更新以后执行一下 `gulp clearCache`

**Comment by MarcoPai** [comment]
好了，多谢多谢！！！

**Comment by minwe** [comment]
客气。
