### ISSUE TITLE
把jquery替换成zepto，并且把zepto也打包到main.js里出现了问题

### ISSUE THREAD

**Issue by psychokiller666** [amazeui/starter-kit#5]
之前用过starter-kit感觉特别好用。

我现在想把jquery改成zepto。

main.js
```javascript
'use strict';

var $ = require('../../node_modules/zepto/zepto.min.js');
// 手淘 flexble布局
require('../../bower_components/lib-flexible/src/flexible.js');
require('../../node_modules/frozenui/js/frozen.js');

// 上拉加载更多
require('../../bower_components/dropload/dist/dropload.js');
// 百度上传组建


console.log( $('.hs-header') );
```

然后使用命令 gulp serve

编译也通过了，没有任何错误提示，

但是zepto运行不了，chrome命令窗口上会提示

Uncaught TypeError: $ is not a function
![](http://i11.tietuku.com/3d706eb67bbfb5d6.jpg)

---

可是我在命令行直接输入 console.log( $('.hs-header') );

看到的

![](http://i11.tietuku.com/b463f6f3690b8da9.jpg)
说明zepto已经加载了

---

如果删除main.js里面的var $ = 

gulp的时候会提示
![](http://i11.tietuku.com/89ff74571b8ddab0.jpg)

**Comment by minwe** [comment]
```js
'use strict';

require('zepto/zepto.min.js');

var $ = window.Zepto;
```

Zepto 打包的文件不支持 CommonJS，只能这样用。

**Comment by psychokiller666** [comment]
谢谢，搞定了。
